name: flutter_glyph_kit
description: Flutter implementation of the Glyph-Developer-Kit by Nothing Technologies Ltd.
version: 0.1.2
homepage: https://github.com/francescovallone/flutter-glyph-kit
repository: https://github.com/francescovallone/flutter-glyph-kit

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.francescovallone.glyph_interface_sdk
        pluginClass: GlyphInterfaceSdkPlugin